/* Generated by RuntimeBrowser.
   Image: /Applications/Skype.app/Contents/MacOS/Skype
 */

@interface DragDestinationTextView : NSTextView  {
//    struct _NSRect { 
//        struct _NSPoint { 
//            float x; 
//            float y; 
//        } origin; 
//        struct _NSSize { 
//            float width; 
//            float height; 
//        } size; 
//    } _previousRect;
    BOOL _acceptsDraggedFiles;
}

@property BOOL acceptsDraggedFiles;


- (void)setAcceptsDraggedFiles:(BOOL)arg1;
- (BOOL)acceptsDraggedFiles;
- (id)getFileForDrag:(id)arg1;
- (id)getFilesForDrag:(id)arg1;
- (BOOL)dragIsFiles:(id)arg1;
- (BOOL)dragIsFile:(id)arg1;
- (void)draggingExited:(id)arg1;
- (void)concludeDragOperation:(id)arg1;
- (id)translateDraggedString:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (unsigned int)draggingUpdated:(id)arg1;
- (unsigned int)draggingEntered:(id)arg1;
- (void)awakeFromNib;

@end
