/* Generated by RuntimeBrowser.
   Image: /Applications/Skype.app/Contents/MacOS/Skype
 */

@class GenericWebView, NSString, BAExternal, NSURL;

@interface GenericWebViewController : NSViewController  {
    BAExternal *_browserAPIExternal;
    NSURL *_initialRequestURL;
    unsigned int _resourceCount;
    unsigned int _resourceFailedCount;
    unsigned int _resourceCompletedCount;
    unsigned int _browserAPISecurityContext;
    BOOL _ownsWindowTitle;
    BOOL _runsInOwnWindow;
    BOOL _stopped;
    BOOL _canReload;
}

@property(readonly) GenericWebView * webView;
@property BOOL ownsWindowTitle;
@property BOOL runsInOwnWindow;
@property(getter=isStopped) BOOL stopped;
@property BOOL canReload;
@property(retain) BAExternal * browserAPIExternal;
@property(readonly) NSString * sourceHTML;
@property(readonly) NSString * sourceURLString;
@property(readonly) NSURL * initialRequestURL;

+ (void)initialize;

- (void)setCanReload:(BOOL)arg1;
- (BOOL)canReload;
- (id)initialRequestURL;
- (void)setBrowserAPIExternal:(id)arg1;
- (id)browserAPIExternal;
- (void)setStopped:(BOOL)arg1;
- (BOOL)isStopped;
- (void)setRunsInOwnWindow:(BOOL)arg1;
- (BOOL)runsInOwnWindow;
- (void)setOwnsWindowTitle:(BOOL)arg1;
- (BOOL)ownsWindowTitle;
- (void)webView:(id)arg1 addMessageToConsole:(id)arg2;
- (id)webView:(id)arg1 createWebViewWithRequest:(id)arg2;
- (BOOL)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (void)webView:(id)arg1 unableToImplementPolicyWithError:(id)arg2 frame:(id)arg3;
- (BOOL)isURLWhiteListed:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)____trackSkypeHack:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForNewWindowAction:(id)arg2 request:(id)arg3 newFrameName:(id)arg4 decisionListener:(id)arg5;
- (void)webView:(id)arg1 decidePolicyForMIMEType:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (void)webView:(id)arg1 resource:(id)arg2 didFailLoadingWithError:(id)arg3 fromDataSource:(id)arg4;
- (id)webView:(id)arg1 identifierForInitialRequest:(id)arg2 fromDataSource:(id)arg3;
- (void)delayedRedirectionToURLRequest:(id)arg1;
- (void)delayedStopLoading:(id)arg1;
- (id)JSAPIRedirectionURLRequestWithRequest:(id)arg1;
- (id)webView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5;
- (void)webView:(id)arg1 willPerformClientRedirectToURL:(id)arg2 delay:(double)arg3 fireDate:(id)arg4 forFrame:(id)arg5;
- (void)scheduleDelayedJSAPIRedirectionWithRequest:(id)arg1;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalLoadForFrame:(id)arg2;
- (void)webView:(id)arg1 didClearWindowObject:(id)arg2 forFrame:(id)arg3;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalLoadWithError:(id)arg2 forFrame:(id)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2 forFrame:(id)arg3;
- (void)webView:(id)arg1 didReceiveTitle:(id)arg2 forFrame:(id)arg3;
- (void)webView:(id)arg1 didStartProvisionalLoadForFrame:(id)arg2;
- (void)handleJavascriptError;
- (void)copyURLCmd:(id)arg1;
- (void)handlePicCloseURL;
- (id)errorTemplateName;
- (id)titleForErrorScreen;
- (void)loadErrorScreenWithErrorString:(id)arg1;
- (void)resourceLoadingFailedWithError:(id)arg1 url:(id)arg2;
- (void)delayedHandleNetworkError:(id)arg1;
- (void)viewSourceAction:(id)arg1;
- (id)sourceURLString;
- (id)sourceHTML;
- (BOOL)isImageURL:(id)arg1;
- (void)close;
- (void)stopLoadingAndClose;
- (void)stopLoading;
- (void)loadURL:(id)arg1;
- (void)loadString:(id)arg1 basePath:(id)arg2;
- (void)loadRequest:(id)arg1;
- (id)webView;
- (void)attachBrowserAPIToWindowScript:(id)arg1;
- (void)dealloc;
- (void)loadView;
- (void)disconnectDelegates;
- (void)setupWebView;

@end
