/* Generated by RuntimeBrowser.
   Image: /Applications/Skype.app/Contents/MacOS/Skype
 */

@class GenericChat, ConversationChatViewController;

@interface GenericChatView : NSView  {
    GenericChat *_chat;
    ConversationChatViewController *_M5ViewController;
}

@property GenericChat * chat;
@property ConversationChatViewController * M5ViewController;


- (void)setM5ViewController:(id)arg1;
- (id)M5ViewController;
- (void)setChat:(id)arg1;
- (id)chat;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)viewDidMoveToSuperview;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (BOOL)isOpaque;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned int)arg3 context:(void*)arg4;
- (void)dealloc;

@end
