/* Generated by RuntimeBrowser.
   Image: /Applications/Skype.app/Contents/MacOS/Skype
 */

#import "DragDestinationTextView.h"

@class NSAttributedString, NSView;

@interface IMTextInputView : DragDestinationTextView  {
    id _target;
    SEL _selector;
    SEL _editLastSelector;
    NSView *_associatedView;
//    struct _NSSize { 
//        float width; 
//        float height; 
//    } _lastPostedSize;
//    struct _NSSize { 
//        float width; 
//        float height; 
//    } _desiredSizeCached;
    int _sleepBetweenTextChangesForDebugging;
    NSAttributedString *attributedPlaceHolderString;
    BOOL _sendingEnabled;
    BOOL _clearOnEscape;
    BOOL _homeToStartOfLine;
    BOOL _resizing;
    BOOL _sendOnEnter;
    BOOL _sendOnReturn;
    BOOL _nextIsReturn;
    BOOL _nextIsEnter;
    BOOL _optionPressedWithNext;
    BOOL _shiftPressedWithNext;
    BOOL _ctrlPressedWithNext;
    BOOL _resizeDesiredFrame;
    BOOL _canSendEmptyContent;
    BOOL _initialFrameSet;
}

@property BOOL clearOnEscape;
@property BOOL canSendEmptyContent;
@property BOOL sendOnEnter;
@property BOOL sendOnReturn;
@property(getter=isInitialFrameSet) BOOL initialFrameSet;
//@property(readonly) struct _NSSize { float x1; float x2; } desiredSize;
@property(readonly) float desiredLineHeight;
@property(retain) NSView * associatedView;

+ (void)initialize;

- (void)setInitialFrameSet:(BOOL)arg1;
- (BOOL)isInitialFrameSet;
- (void)setSendOnReturn:(BOOL)arg1;
- (BOOL)sendOnReturn;
- (void)setSendOnEnter:(BOOL)arg1;
- (BOOL)sendOnEnter;
- (void)setCanSendEmptyContent:(BOOL)arg1;
- (BOOL)canSendEmptyContent;
- (void)setAssociatedView:(id)arg1;
- (id)associatedView;
- (void)setClearOnEscape:(BOOL)arg1;
- (BOOL)clearOnEscape;
- (id)menu;
- (BOOL)validateMenuItem:(id)arg1;
- (void)toggleSmartInsertDelete:(id)arg1;
- (void)toggleAutomaticQuoteSubstitution:(id)arg1;
- (void)toggleAutomaticDataDetection:(id)arg1;
- (void)toggleAutomaticDashSubstitution:(id)arg1;
- (void)toggleAutomaticLinkDetection:(id)arg1;
- (void)toggleAutomaticTextReplacement:(id)arg1;
- (void)toggleAutomaticSpellingCorrection:(id)arg1;
- (void)toggleGrammarChecking:(id)arg1;
- (void)toggleContinuousSpellChecking:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)viewWillMoveToWindow:(id)arg1;
//- (void)drawRect:(struct _NSRect { struct _NSPoint { float x_1_1_1; float x_1_1_2; } x1; struct _NSSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setPlaceholderString:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)changeFont:(id)arg1;
- (void)interpretKeyEvents:(id)arg1;
- (void)insertText:(id)arg1;
- (void)keyDown:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)editLastMessage:(id)arg1;
- (void)sendContent:(id)arg1;
- (void)setTarget:(id)arg1 action:(SEL)arg2 editLastAction:(SEL)arg3;
- (void)cancelOperation:(id)arg1;
- (void)textDidChange:(id)arg1;
- (void)frameDidChange:(id)arg1;
- (void)SK_resetCacheAndPostSizeChanged;
//- (struct _NSSize { float x1; float x2; })desiredSize;
- (float)desiredLineHeight;
- (void)setString:(id)arg1;
- (void)setAttributedString:(id)arg1;
- (id)translateDraggedString:(id)arg1;
- (void)performFindPanelAction:(id)arg1;
- (void)paste:(id)arg1;
- (BOOL)becomeFirstResponder;
- (void)dealloc;
- (void)textDidEndEditing:(id)arg1;
- (void)SK_initIMTextInputView;
- (id)initWithCoder:(id)arg1;
//- (id)initWithFrame:(struct _NSRect { struct _NSPoint { float x_1_1_1; float x_1_1_2; } x1; struct _NSSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 textContainer:(id)arg2;
- (void)resetTextAttributes:(id)arg1;
- (void)setPlainTextMode:(id)arg1;
- (void)setRichTextMode:(id)arg1;
- (void)toggleTextMode:(id)arg1;

@end
