/* Generated by RuntimeBrowser.
   Image: /Applications/Skype.app/Contents/MacOS/Skype
 */

@class <SkypeChatWebViewWindowObservingDelegate>;

@interface SkypeChatWebView : WebView  {
    id _draggingDelegate;
    <SkypeChatWebViewWindowObservingDelegate> *_windowObservingDelegate;
    BOOL _allowsDragAndDrop;
}

@property id draggingDelegate;
@property <SkypeChatWebViewWindowObservingDelegate> * windowObservingDelegate;
@property BOOL allowsDragAndDrop;


- (void)setAllowsDragAndDrop:(BOOL)arg1;
- (BOOL)allowsDragAndDrop;
- (void)setWindowObservingDelegate:(id)arg1;
- (id)windowObservingDelegate;
- (void)magnifyWithEvent:(id)arg1;
- (void)broadCastTextSizeMultiplierChange;
- (void)makeTextStandardSize:(id)arg1;
- (void)makeTextSmaller:(id)arg1;
- (void)makeTextLarger:(id)arg1;
- (struct _NSRect { struct _NSPoint { float x_1_1_1; float x_1_1_2; } x1; struct _NSSize { float x_2_1_1; float x_2_1_2; } x2; })adjustScroll:(struct _NSRect { struct _NSPoint { float x_1_1_1; float x_1_1_2; } x1; struct _NSSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (BOOL)resignFirstResponder;
- (void)selectAll:(id)arg1;
- (void)SK_highlightDragDestinationOnUpdate;
- (void)SK_highlightDragDestinationOnEnter;
- (void)concludeDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (unsigned int)draggingUpdated:(id)arg1;
- (unsigned int)draggingEntered:(id)arg1;
- (id)draggingDelegate;
- (void)setDraggingDelegate:(id)arg1;
- (id)fontFamily;
- (void)setFontFamily:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)setHostWindow:(id)arg1;
- (void)performFindPanelAction:(id)arg1;
- (BOOL)isOpaque;
- (void)dealloc;
- (id)initWithFrame:(struct _NSRect { struct _NSPoint { float x_1_1_1; float x_1_1_2; } x1; struct _NSSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 frameName:(id)arg2 groupName:(id)arg3;

@end
