/* Generated by RuntimeBrowser.
   Image: /Applications/Skype.app/Contents/MacOS/Skype
 */

@class SkypeChat, MacContact, NSString, NSMenu, MacParticipant;

@interface SkypeChatContact : NSObject /*<MacContactDelegate, MacParticipantDelegate>*/ {
    SkypeChat *_ownerChat;
    MacContact *_contact;
    MacParticipant *_participant;
    unsigned int _objectID;
    NSString *_identity;
    BOOL _typing;
    BOOL _wasBlocked;
}

@property(readonly) int type;
@property(readonly) unsigned int skypeObjectID;
@property(readonly) NSString * identity;
@property(readonly) NSString * displayName;
@property(readonly) NSString * displayNameXMLEscaped;
@property(readonly) MacContact * macContact;
@property(readonly) BOOL isBuddy;
@property(readonly) BOOL isXMPP;
@property(readonly) NSString * smsPhone;
@property(readonly) int textStatus;
@property(readonly) int availability;
@property(readonly) BOOL doesAppearOnline;
@property(readonly) NSMenu * callSubMenu;
@property(readonly) NSMenu * menu;
@property(readonly) BOOL hasAuthorizedMe;
@property(readonly) BOOL isAuthorized;
@property(readonly) BOOL isSkypeContact;
@property(readonly) BOOL isPSTNContact;
@property(readonly) BOOL canReceiveSMS;
@property(readonly) BOOL isDialogPartner;
@property(readonly) SkypeChat * chat;
@property(readonly) int rank;
@property BOOL typing;
@property NSString * lastSentSMSNumber;


- (unsigned int)skypeObjectID;
- (id)identity;
- (id)chat;
- (void)kickAndBanMemberCmd:(id)arg1;
- (void)kickMemberCmd:(id)arg1;
- (void)acceptApplicant:(id)arg1;
- (void)setRankToCmd:(id)arg1;
- (void)SK_blockContactAlertDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void*)arg3;
- (void)blockUserCmd:(id)arg1;
- (void)SK_removeContactAlertDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void*)arg3;
- (void)removeContactCmd:(id)arg1;
- (void)addContactCmd:(id)arg1;
- (void)showProfileCmd:(id)arg1;
- (void)sendContactPickerDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void*)arg3;
- (void)sendContactsCmd:(id)arg1;
- (void)sendFileCmd:(id)arg1;
- (void)SMSCmd:(id)arg1;
- (void)chatCmd:(id)arg1;
- (void)callCmd:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (id)menu;
- (id)callSubMenu;
- (void)SK_handleParticipantTextStatusChanged;
- (void)macParticipantDidReceiveDTMF:(id)arg1;
- (void)macParticipantDidChange:(id)arg1;
- (void)SK_handleChatContactAvailabilityDidChange;
- (void)macContactDidChange:(id)arg1;
- (void)setLastSentSMSNumber:(id)arg1;
- (id)lastSentSMSNumber;
- (BOOL)hasContactProperty:(int)arg1;
- (void)removeMacContactAndChatMemberDelegate;
- (void)chatIsDeallocated;
- (int)textStatus;
- (void)refreshProfile;
- (id)smsPhone;
- (BOOL)doesAppearOnline;
- (int)availability;
- (BOOL)hasCapability:(int)arg1;
- (BOOL)isDialogPartner;
- (BOOL)isPSTNContact;
- (BOOL)isSkypeContact;
- (int)type;
- (BOOL)canSetRankTo:(int)arg1;
- (BOOL)setRankTo:(int)arg1;
- (int)rank;
- (BOOL)canReceiveSMS;
- (BOOL)isAuthorized;
- (BOOL)hasAuthorizedMe;
- (BOOL)isXMPP;
- (BOOL)isBuddy;
- (void)setBuddyStatus:(BOOL)arg1;
- (void)setBlock:(BOOL)arg1;
- (BOOL)isBlocked;
- (id)displayNameXMLEscaped;
- (id)displayName;
- (void)setDisplayName:(id)arg1;
- (id)macContact;
- (void)setTyping:(BOOL)arg1;
- (BOOL)typing;
- (id)description;
- (void)dealloc;
- (void)commonInit;
- (id)initWithChatMemberID:(unsigned int)arg1 chat:(id)arg2;
- (id)initWithContactIdentity:(id)arg1 contactID:(unsigned int)arg2 chat:(id)arg3;
- (id)initWithContactIdentity:(id)arg1 chat:(id)arg2;
- (id)init;
- (BOOL)hasSMSNumber;

@end
