/* Generated by RuntimeBrowser.
   Image: /Applications/Skype.app/Contents/MacOS/Skype
 */

@class NSString, NSMutableDictionary;

@interface SkypeChatStyle : NSObject <ChatStyle> {
    NSString *_styleName;
    NSString *_stylePath;
    unsigned int _styleVersion;
    NSString *_styleBundleVersion;
    NSMutableDictionary *_styleTemplates;
    NSString *_fontFace;
    float _fontSize;
    BOOL _showUserIcons;
    BOOL _isFontSet;
    BOOL _formattedCopyCompatible;
    BOOL _supportsStoredRender;
}

@property(readonly) unsigned int styleVersion;
@property(readonly) NSString * name;
@property(readonly) NSString * styleBundleVersion;
@property(readonly) NSString * stylePath;
@property(readonly) NSString * contentInHTML;
@property(readonly) NSString * nextContentInHTML;
@property(readonly) NSString * contentOutHTML;
@property(readonly) NSString * nextContentOutHTML;
@property(readonly) NSString * smsInHTML;
@property(readonly) NSString * smsOutHTML;
@property(readonly) NSString * smsHeadHTML;
@property(readonly) NSString * statusHTML;
@property(readonly) NSString * emoteOutHTML;
@property(readonly) NSString * emoteInHTML;
@property(readonly) NSString * typingHTML;
@property(readonly) NSString * moreHistoryHTML;
@property(readonly) NSString * moreHistoryLinkHTML;
@property(readonly) NSString * transferOutHTML;
@property(readonly) NSString * transferInHTML;
@property(readonly) NSString * subTransferOutHTML;
@property(readonly) NSString * subTransferInHTML;
@property(readonly) NSString * transferHeadOutHTML;
@property(readonly) NSString * voicemailInHTML;
@property(readonly) NSString * callStartHTML;
@property(readonly) NSString * callEndHTML;
@property(readonly) NSString * skypeCallStartHTML;
@property(readonly) NSString * skypeCallEndHTML;
@property(readonly) NSString * videoMessageInHTML;
@property(readonly) NSString * videoMessageOutHTML;
@property(readonly) NSString * templatePath;
@property(readonly) NSString * fontFace;
@property(readonly) BOOL showUserIcons;
@property(readonly) BOOL isFontSet;
@property(readonly) BOOL formattedCopyCompatible;
@property(readonly) BOOL supportsStoredRender;
@property(readonly) int nameFormat;
@property(readonly) float fontSize;

+ (void)makeChatStylesDirectory;
+ (BOOL)isFontSetForStyle:(id)arg1;
+ (void)setFontSize:(float)arg1 forStyle:(id)arg2;
+ (void)setFontFace:(id)arg1 forStyle:(id)arg2;
+ (float)fontSizeForStyle:(id)arg1;
+ (id)fontFaceForStyle:(id)arg1;
+ (id)stylePathDictionary;
+ (void)initialize;

- (id)templatePath;
- (id)SK_loadStyleFiles:(id)arg1 withCSS:(id)arg2 styleName:(id)arg3;
- (float)fontSize;
- (id)fontFace;
- (BOOL)isFontSet;
- (int)nameFormat;
- (BOOL)supportsStoredRender;
- (BOOL)formattedCopyCompatible;
- (BOOL)showUserIcons;
- (id)stylePath;
- (id)styleBundleVersion;
- (unsigned int)styleVersion;
- (id)loadStyleAndMakeTemplate:(id)arg1 andVariant:(id)arg2;
- (id)name;
- (void)dealloc;
- (id)init;
- (id)videoMessageOutHTML;
- (id)videoMessageInHTML;
- (id)skypeCallEndHTML;
- (id)skypeCallStartHTML;
- (id)callEndHTML;
- (id)callStartHTML;
- (id)voicemailInHTML;
- (id)smsHeadHTML;
- (id)smsOutHTML;
- (id)smsInHTML;
- (id)transferHeadOutHTML;
- (id)subTransferInHTML;
- (id)subTransferOutHTML;
- (id)transferInHTML;
- (id)transferOutHTML;
- (id)moreHistoryLinkHTML;
- (id)moreHistoryHTML;
- (id)typingHTML;
- (id)emoteInHTML;
- (id)emoteOutHTML;
- (id)statusHTML;
- (id)contentInHTML;
- (id)nextContentInHTML;
- (id)contentOutHTML;
- (id)nextContentOutHTML;

@end
